### ISSUE TITLE
Unhandled Opcode 00

### ISSUE THREAD

**Issue by xiphffff** [Elyotna/IntWars#130]
It's probably my fault somehow, but I get nothing but:

WARNING	22:03:47	D:\IntWars-master\gamed\src\PacketHandler.cpp	handlePacket:208	Unhandled OpCode 00
INFO	22:03:47	D:\IntWars-master\gamed\src\PacketHandler.cpp	printPacket:105	Printing packet with size 6 0000-0005 00 00 00 00 00 00 ...... \x00\x00\x00\x00\x00\x00

I haven't seen anything else related to this, suggestions?

**Comment by Querijn** [comment]
Please don't use any other version than is mentioned on the forum that is supported.
