### ISSUE TITLE
All spells do not deal any damage.

### ISSUE THREAD

**Issue by NitroXenon** [Elyotna/IntWars#133]
No spell can deal damage...
Can someone fix it? :+1:

**Comment by ghost** [comment]
Make IntWars point to 4.20 files; Edit line 40 in main.cpp
I believe 704d9f3a6fa63a06125c0294a1e4a1f81d7e5904 is what's causing your problem.

**Comment by NitroXenon** [comment]
@joaquin95 Solved. Thanks for your help :P
